import { DonationLog } from "../../screens/Main/MyDonationsScreen/components/DonationItem";
import { UrgentRequest } from "../../screens/Main/HomeScreen/types";
import { BloodRequest } from "../../screens/Main/FeedScreen/types";
import { ChatThread } from "../../screens/Main/ChatsListScreen/components/ChatItem";
import { Alert } from "../../screens/Main/NotificationsScreen/types";

export const MOCK_DONATIONS: DonationLog[] = [
  {
    id: "log_1",
    hospitalName: "Mayo Hospital",
    date: "2026-03-12",
    units: 1,
    bloodType: "O+",
    request: {
      id: "req_1",
      bloodType: "O+",
      patientName: "Ahmed Khan",
      hospital: "Mayo Hospital",
      city: "Lahore",
      units: 3,
      urgency: "critical",
      time: "2h ago",
      distance: "3.2 km",
    },
  },
  {
    id: "log_2",
    hospitalName: "Jinnah Hospital",
    date: "2025-12-10",
    units: 1,
    bloodType: "A-",
    request: {
      id: "req_2",
      bloodType: "A-",
      patientName: "Sara Malik",
      hospital: "Jinnah Hospital",
      city: "Lahore",
      units: 2,
      urgency: "urgent",
      time: "4h ago",
      distance: "5.1 km",
    },
  },
  {
    id: "log_3",
    hospitalName: "Shaukat Khanum Hospital",
    date: "2025-08-15",
    units: 1,
    bloodType: "B+",
    request: {
      id: "req_3",
      bloodType: "B+",
      patientName: "Bilal Raza",
      hospital: "Shaukat Khanum Hospital",
      city: "Lahore",
      units: 4,
      urgency: "critical",
      time: "30m ago",
      distance: "7.0 km",
    },
  },
  {
    id: "log_4",
    hospitalName: "Services Hospital",
    date: "2025-05-05",
    units: 2,
    bloodType: "AB-",
    request: {
      id: "req_4",
      bloodType: "AB-",
      patientName: "Zubair Ahmad",
      hospital: "Services Hospital",
      city: "Lahore",
      units: 2,
      urgency: "normal",
      time: "1d ago",
      distance: "1.5 km",
    },
  },
  {
    id: "log_5",
    hospitalName: "General Hospital",
    date: "2025-02-01",
    units: 1,
    bloodType: "O-",
    request: {
      id: "req_5",
      bloodType: "O-",
      patientName: "Fatima Bibi",
      hospital: "General Hospital",
      city: "Lahore",
      units: 1,
      urgency: "normal",
      time: "3d ago",
      distance: "8.0 km",
    },
  },
];

export const MOCK_URGENT_REQUESTS: UrgentRequest[] = [
  {
    id: "1",
    bloodType: "B+",
    hospital: "Mayo Hospital",
    city: "Lahore",
    state: "Punjab",
    patientImage:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&h=150&fit=crop",
    units: 3,
    urgency: "critical",
    time: "2h ago",
    distance: "3.2 km",
    latitude: 31.5723,
    longitude: 74.3213,
  },
  {
    id: "2",
    bloodType: "A-",
    hospital: "Jinnah Hospital",
    city: "Lahore",
    state: "Punjab",
    patientImage:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    units: 2,
    urgency: "urgent",
    time: "4h ago",
    distance: "5.1 km",
    latitude: 31.4806,
    longitude: 74.303,
  },
  {
    id: "3",
    bloodType: "O-",
    hospital: "Services Hospital",
    city: "Lahore",
    state: "Punjab",
    patientImage:
      "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&h=150&fit=crop",
    units: 1,
    urgency: "normal",
    time: "6h ago",
    distance: "1.8 km",
    latitude: 31.5428,
    longitude: 74.3364,
  },
];

export const MOCK_REQUESTS: BloodRequest[] = [
  {
    id: "1",
    bloodType: "B+",
    patientName: "Ahmed Khan",
    hospital: "Mayo Hospital",
    city: "Lahore",
    state: "Punjab",
    patientImage:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&h=150&fit=crop",
    units: 3,
    urgency: "critical",
    time: "2h ago",
    distance: "3.2 km",
    latitude: 31.5723,
    longitude: 74.3213,
  },
  {
    id: "2",
    bloodType: "A-",
    patientName: "Sara Malik",
    hospital: "Jinnah Hospital",
    city: "Lahore",
    state: "Punjab",
    patientImage:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    units: 2,
    urgency: "urgent",
    time: "4h ago",
    distance: "5.1 km",
    latitude: 31.4806,
    longitude: 74.303,
  },
  {
    id: "3",
    bloodType: "O+",
    patientName: "Anonymous",
    hospital: "Services Hospital",
    city: "Lahore",
    state: "Punjab",
    patientImage:
      "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&h=150&fit=crop",
    units: 1,
    urgency: "normal",
    time: "6h ago",
    distance: "1.8 km",
    latitude: 31.5428,
    longitude: 74.3364,
  },
  {
    id: "4",
    bloodType: "AB-",
    patientName: "Bilal Raza",
    hospital: "Shaukat Khanum",
    city: "Lahore",
    state: "Punjab",
    patientImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
    units: 4,
    urgency: "critical",
    time: "30m ago",
    distance: "7.0 km",
    latitude: 31.4285,
    longitude: 74.2796,
  },
];

export const MOCK_THREADS: ChatThread[] = [
  {
    id: "thread_1",
    request: {
      id: "1",
      bloodType: "B+",
      patientName: "Ahmed Khan",
      hospital: "Mayo Hospital",
      city: "Lahore",
      patientImage:
        "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&h=150&fit=crop",
      units: 3,
      urgency: "critical",
      time: "2h ago",
      distance: "3.2 km",
      latitude: 31.5723,
      longitude: 74.3213,
    },
    lastMessage: "We urgently need 3 units at Mayo Hospital. Are you available?",
    time: "2h ago",
    unreadCount: 2,
    isOnline: true,
  },
  {
    id: "thread_2",
    request: {
      id: "4",
      bloodType: "AB-",
      patientName: "Bilal Raza",
      hospital: "Shaukat Khanum",
      city: "Lahore",
      patientImage:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
      units: 4,
      urgency: "critical",
      time: "30m ago",
      distance: "7.0 km",
      latitude: 31.4285,
      longitude: 74.2796,
    },
    lastMessage: "Bless you! What time are you planning to visit?",
    time: "30m ago",
    unreadCount: 0,
    isOnline: true,
  },
  {
    id: "thread_3",
    request: {
      id: "2",
      bloodType: "A-",
      patientName: "Sara Malik",
      hospital: "Jinnah Hospital",
      city: "Lahore",
      patientImage:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
      units: 2,
      urgency: "urgent",
      time: "4h ago",
      distance: "5.1 km",
      latitude: 31.4806,
      longitude: 74.303,
    },
    lastMessage: "Thank you so much! Please coordinate with the receptionist.",
    time: "Yesterday",
    unreadCount: 0,
    isOnline: false,
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "1",
    type: "blood_request",
    title: "Urgent: B+ Blood Needed",
    body: "Mayo Hospital in Lahore urgently needs 3 units of B+ blood.",
    time: "2m ago",
    read: false,
    urgency: "critical",
    bloodType: "B+",
    hospital: "Mayo Hospital",
  },
  {
    id: "2",
    type: "donation_match",
    title: "You're a Match!",
    body: "A patient near you needs O+ blood. You last donated 4 months ago — you may be eligible.",
    time: "18m ago",
    read: false,
    bloodType: "O+",
  },
  {
    id: "3",
    type: "blood_request",
    title: "Urgent: A- Blood Needed",
    body: "Jinnah Hospital requires 2 units of A- blood for an emergency case.",
    time: "1h ago",
    read: false,
    urgency: "urgent",
    bloodType: "A-",
    hospital: "Jinnah Hospital",
  },
  {
    id: "4",
    type: "reminder",
    title: "You Can Donate Again",
    body: "It has been 90 days since your last donation. You are now eligible to donate blood.",
    time: "3h ago",
    read: true,
  },
  {
    id: "5",
    type: "donation_match",
    title: "Request Fulfilled",
    body: "The blood request you responded to at Services Hospital has been fulfilled. Thank you!",
    time: "Yesterday",
    read: true,
  },
  {
    id: "6",
    type: "system",
    title: "Profile Verified",
    body: "Your donor profile has been verified. You will now receive priority match alerts.",
    time: "2 days ago",
    read: true,
  },
];
