import { moderateScale } from "react-native-size-matters";

export const fontFamily = {
  BLACK: "Montserrat-Black",
  BOLD: "Montserrat-Bold",
  EXTRABOLD: "Montserrat-ExtraBold",
  EXTRALIGHT: "Montserrat-ExtraLight",
  LIGHT: "Montserrat-Light",
  MEDIUM: "Montserrat-Medium",
  REGULAR: "Montserrat-Regular",
  SEMIBOLD: "Montserrat-SemiBold",
  THIN: "Montserrat-Thin",
};

export const fontSize = {
  FONT_48: moderateScale(48),
  FONT_44: moderateScale(44),
  FONT_40: moderateScale(40),
  FONT_38: moderateScale(38),
  FONT_36: moderateScale(36),
  FONT_34: moderateScale(34),
  FONT_32: moderateScale(32),
  FONT_30: moderateScale(30),
  FONT_28: moderateScale(28),
  FONT_26: moderateScale(26),
  FONT_24: moderateScale(24),
  FONT_22: moderateScale(22),
  FONT_20: moderateScale(20),
  FONT_18: moderateScale(18),
  FONT_16: moderateScale(16),
  FONT_15: moderateScale(15),
  FONT_14: moderateScale(14),
  FONT_13: moderateScale(13),
  FONT_12: moderateScale(12),
  FONT_11: moderateScale(11),
  FONT_10: moderateScale(10),
  FONT_9: moderateScale(9),
  FONT_8: moderateScale(8),
  FONT_6: moderateScale(6),
};
